'use strict'

const videoshow = require('videoshow');
const images = ['./images/home-design/interior-design-expert-reveals-the-simple-tips-which-can.jpg',
    './images/home-design/september-kerala-home-design-and-floor-plans-in.jpg',
    './images/home-design/home-design-house-design-in-house-front-design.jpg',
    './images/home-design/home-design-decor-interior-design-for-house-in.jpg',
    './images/home-design/modern-home-design-for-feet-by-feet-plot-acha-homes.jpg',
    './images/home-design/best-ideas-about-modern-house-exteriors-on-pinterest.jpg',
    './images/home-design/house-plan-sqft-floor-planbhk-home-design.jpg',
    './images/home-design/kerala-home-design.jpg',
    './images/home-design/maharashtra-house-design-d-exterior-design.jpg',
    './images/home-design/small-home-design-plan-xm-with-bedrooms.jpg',
    './images/home-design/a-stunning-house-plan-in-feet-by-feet-with-bedrooms.jpg',
    './images/home-design/d-home-designs-sonipat-ho-interior-designers-for-temple.jpg',
    './images/home-design/sqft-keralahouseplannercom.jpg',
    './images/home-design/bedroom-sq-ft-arabian-style-home-design-kerala-home.jpg',
    './images/home-design/home-design-customize-your-house-with-new-design-platform.jpg',
    './images/home-design/d-home-designs-associates-muzaffar-nagar-city-exterior.jpg',
    './images/home-design/house-design-simple-low-cost.jpg',
    './images/home-design/d-home-designs-sonipat-ho-interior-designers-for-temple.jpg',
    './images/home-design/kerala-style-sqft-villa-design-traditional-double-floor.jpg',
    './images/home-design/ft-x-ft-d-house-plan-and-elevation-design-with-interior.jpg',
    './images/home-design/best-plan-for-house-design-in-nepal-home-design-ideas.jpg',
    './images/home-design/kerala-home-design-house-designs-may.jpg',
    './images/home-design/d-home-designs-sonipat-ho-interior-designers-for-temple.jpg',
    './images/home-design/d-exterior-house-design-single-family-home-by.jpg',
    './images/home-design/elements-of-interior-design-launchpad-academy.png',
    './images/home-design/ideas-for-a-modern-house-design-fontan-architecture.jpg',
    './images/home-design/house-design-md-house-builders-in-sri-lanka-home.jpg',
    './images/home-design/sky-house-design-centre-sky-house-design-centre.jpg',
    './images/home-design/modern-house-design-durga-sthan-manddir-architects-in.jpg',
    './images/home-design/floor-house-design-in-india.jpg',
    './images/home-design/low-cost-home-design-ideas-everyone-will-like-acha-homes.jpg',
    './images/home-design/xm-simple-home-design-plan-with-bedrooms-sketchup-modeling-house-plans.jpg',
    './images/home-design/simple-contemporary-home-design-kerala-home-design.jpg',
    './images/home-design/beautiful-dream-home-design-in-sqfeet-kerala-home.jpg',
    './images/home-design/home-designs-new-home-designs-melbourne-brisbane-orbit.jpg',
    './images/home-design/interior-design-ideas-home-decorating-inspiration.png',
    './images/home-design/home-designs-perth-new-house-design-floorplans.jpg',
    './images/home-design/best-home-decorating-ideas-top-designer-decor-tricks.jpg',
    './images/home-design/house-plans-in-sri-lanka-amazing-house-planskedallalk.jpg',
    './images/home-design/an-open-sanctuary-a-modern-filipino-home-design-by-budji.jpg',
    './images/home-design/minimalist-interior-design-singapore.jpg',
    './images/home-design/top-modern-house-designs-ever-built-architecture-beast.jpg',
    './images/home-design/home-design-magazine-home-design-interior-design.jpg',
    './images/home-design/new-home-design-lakh.jpg',
    './images/home-design/modsy-review-is-this-new-interior-home-design-service-worth-it.jpg',
    './images/home-design/interior-design-ideas-home-decorating-inspiration.jpg',
    './images/home-design/home-designs-perth-new-house-design-floorplans.jpg',
    './images/home-design/free-and-online-d-home-design-planner-homebyme.jpg',
    './images/home-design/home-design-roomsketcher.jpg',
    './images/home-design/remodeling-software-home-designer.jpg',
    './images/home-design/home-design-rajasthan-homeriview.jpg',
    './images/home-design/oyo-home-design-studio-nagoa-goa-goa-hotel-reviews.jpg',
    './images/home-design/home-designs-perth-new-house-design-floorplans.jpg',
    './images/home-design/d-home-designs-associates-muzaffar-nagar-city-exterior.jpg',
    './images/home-design/e-spectrum-interiors-best-interior-designers-in-kerala.jpg',
    './images/home-design/luxurious-modern-home-design-in-ampang-design-renovation.jpg',
    './images/home-design/architecturally-designed-kit-homes-imagine-kit-homes.jpg',
    './images/home-design/royal-interior-design-ltd-interior-design-firm-in-stouffville.jpg',
    './images/home-design/house-design-in-first-floor.jpg',
    './images/home-design/interior-design-hacks-five-seasoned-experts-reveal-their-go.jpg',
    './images/home-design/home-design-trends-for-home-design-news-top.jpg',
    './images/home-design/in-progress-interior-design.jpg',
    './images/home-design/home-designs-for-feet-by-feet-plot-acha-homes.jpg',
    './images/home-design/d-home-designs-associates-photos-muzaffar-nagar-city.jpg',
    './images/home-design/home-design-magazine-home-design-interior-design.jpg',
    './images/home-design/home-design-for-android-apk-download.jpg',
    './images/home-design/kavtek-ar-app-review-home-design-at-our-fingertips-arpost.png',
    './images/home-design/california-homedesign-your-online-home-design-directory.jpg',
    './images/home-design/plan-jd-narrow-lot-modern-house-plan.jpg',
    './images/home-design/building-design-wikipedia.jpg',
    './images/home-design/maximizing-your-home-design-mansion-global.jpeg',
    './images/home-design/mpg-home-design-architecture-interior-design.jpg',
    './images/home-design/phoenix-interior-design-and-interior-designers-in-scottsdale.jpg',
    './images/home-design/home-design-trends-that-are-hot-and-that-are.jpg',
    './images/home-design/registered-interior-design-services-company-singapore.png',
    './images/home-design/home-interior-designers-in-chennai-interior-design-for.jpg',
    './images/home-design/the-best-home-design-apps-for-android-iphone-and-ipad.jpg',
    './images/home-design/home-calgary-interior-design-decorating-and-renovations.jpg',
    './images/home-design/dream-home-interior-all-solutions-no-interior-service-and.jpg',
    './images/home-design/best-san-francisco-home-goods-and-furniture-stores-curbed-sf.jpeg',
    './images/home-design/home-design-magazine-home-design-interior-design.jpg',
    './images/home-design/interior-designer-reveals-the-biggest-mistakes-people-make.jpg',
    './images/home-design/design-build-remodeler-minneapolis-mn-remodeling-and.jpg',
    './images/home-design/tk-home-design.jpg',
    './images/home-design/homeofficemodular-kitchenswardrobesinterior-designers.jpg',
    './images/home-design/online-interior-design-with-modsy-living-rooms-dining.jpg',
    './images/home-design/contemporary-interior-design-striking-and-sleek-rooms.jpg',
    './images/home-design/interior-design-london-studio-commercial-residenial-projects.jpg',
    './images/home-design/wayfair-design-services.jpg',
    './images/home-design/tips-to-improve-your-home-interior-design-manglam-group.jpg',
    './images/home-design/best-home-decorating-ideas-top-designer-decor-tricks.jpg',
    './images/home-design/cabo-interior-design-home-decor-los-cabos-interior-designer.jpg',
    './images/home-design/best-living-room-ideas-stylish-living-room-decorating.jpg',
    './images/home-design/office-interior-design-ideas-office-decorating-ad-india.jpg',
    './images/home-design/triple-heart-design-top-interior-design-firm-in-austin-tx.jpg',
    './images/home-design/the-design-awards-andrew-martin.jpg',
    './images/home-design/bunglow-design-d-architectural-rendering-services-d.jpg']

var videoOptions = {
    fps: 25,
    loop: 5, // seconds
    transition: true,
    transitionDuration: 1, // seconds
    videoBitrate: 1024,
    videoCodec: 'libx264',
    size: '640x?',
    audioBitrate: '128k',
    audioChannels: 2,
    format: 'mp4',
    pixelFormat: 'yuv420p'
}

videoshow(images, videoOptions)
    .save('./video.mp4')
    .on('start', function (command) {
        console.log('ffmpeg process started:', command)
    })
    .on('error', function (err, stdout, stderr) {
        console.error('Error:', err)
        console.error('ffmpeg stderr:', stderr)
    })
    .on('end', function (output) {
        console.error('Video created in:', output)
    })